### ISSUE TITLE
Would you mind cutting a small bug fix release? (v.0.5.1)

### ISSUE THREAD

**Issue by cristianrasch** [j0ack/flask-inertia#10]
Hi again! Really sorry to bother you and I hate to ask, but it'd be great to be able to just pip install (i.e. pull a new version from PyPi) that includes that Partial Data fix I need to stop using my monkeypatched version of the library.

I don't want to bother you with the details, but at work we mostly use Poetry (I know, *sighs*) to manage our project dependencies, and it has issues building the package from source (for some reason, it won't install the project deps specified in the requirements.txt file in the temp venv it creates)

```
$ poetry add git+https://github.com/j0ack/flask-inertia.git

Unable to determine package info for path: /home/cristian/Documents/workspace/1p21/time_tracker_webapp/.venv/src/flask-inertia

Command ['/tmp/tmpho050ql5/.venv/bin/python', '-'] errored with the following return code 1

Output:
Traceback (most recent call last):
  File "/tmp/tmpho050ql5/.venv/lib/python3.11/site-packages/build/__init__.py", line 466, in _handle_backend
    yield
  File "/tmp/tmpho050ql5/.venv/lib/python3.11/site-packages/build/__init__.py", line 356, in get_requires_for_build
    return set(get_requires(config_settings))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmpho050ql5/.venv/lib/python3.11/site-packages/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmpho050ql5/.venv/lib/python3.11/site-packages/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/tmp/tmpho050ql5/.venv/lib/python3.11/site-packages/build/__init__.py", line 302, in _runner
    self._hook_runner(cmd, cwd, extra_environ)
  File "/tmp/tmpho050ql5/.venv/lib/python3.11/site-packages/pyproject_hooks/_impl.py", line 71, in quiet_subprocess_runner
    check_output(cmd, cwd=cwd, env=env, stderr=STDOUT)
  File "/home/cristian/.asdf/installs/python/3.11.4/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cristian/.asdf/installs/python/3.11.4/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/tmp/build-env-swdqwqop/bin/python', '/tmp/tmpho050ql5/.venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py', 'get_requires_for_build_wheel', '/tmp/tmpljv0jdpj']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 16, in <module>
  File "/tmp/tmpho050ql5/.venv/lib/python3.11/site-packages/build/__init__.py", line 355, in get_requires_for_build
    with self._handle_backend(hook_name):
  File "/home/cristian/.asdf/installs/python/3.11.4/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/tmp/tmpho050ql5/.venv/lib/python3.11/site-packages/build/__init__.py", line 474, in _handle_backend
    raise BuildBackendException(  # noqa: B904 # use raise from
build.BuildBackendException: Backend subprocess exited when trying to invoke get_requires_for_build_wheel


Input:
import build
import build.env
import pyproject_hooks

source = '/home/cristian/Documents/workspace/1p21/time_tracker_webapp/.venv/src/flask-inertia'
dest = '/tmp/tmpho050ql5/dist'

with build.env.IsolatedEnvBuilder() as env:
    builder = build.ProjectBuilder(
        srcdir=source,
        scripts_dir=env.scripts_dir,
        python_executable=env.executable,
        runner=pyproject_hooks.quiet_subprocess_runner,
    )
    env.install(builder.build_system_requires)
    env.install(builder.get_requires_for_build('wheel'))
    builder.metadata_path(dest)

Fallback egg_info generation failed.

Command ['/tmp/tmpho050ql5/.venv/bin/python', 'setup.py', 'egg_info'] errored with the following return code 1

Output:
Traceback (most recent call last):
  File "/home/cristian/Documents/workspace/1p21/time_tracker_webapp/.venv/src/flask-inertia/setup.py", line 38, in <module>
    from flask_inertia import __version__
  File "/home/cristian/Documents/workspace/1p21/time_tracker_webapp/.venv/src/flask-inertia/flask_inertia/__init__.py", line 34, in <module>
    from flask_inertia.inertia import Inertia
  File "/home/cristian/Documents/workspace/1p21/time_tracker_webapp/.venv/src/flask-inertia/flask_inertia/inertia.py", line 36, in <module>
    from flask import Flask, Response, current_app, request
ModuleNotFoundError: No module named 'flask'
```

I can install it just fine if I add this minimum pyproject.toml to my fork of the project and then issue a simple: poetry add ../flask-inertia (I did this to verify that this is mostly a Poetry related issue and unlikely to also affect other users of the lib)

```
[tool.poetry]
name = "flask-inertia"
version = "0.5"
description = "Inertiajs Adapter for Flask."
authors = ["TROUVERIE Joachim <jtrouverie@joakode.fr>"]
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.8"
flask = ">=1.1.2"
jsmin = ">=2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

**Comment by j0ack** [comment]
Hello,

As mentioned [here](https://github.com/j0ack/flask-inertia/pull/5#issuecomment-1772263452) I'll release a new version today including the last PRs later today on Pypi.

You'll then be able to install it from there
